name: Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install gatsby cli
        run: npm install --location=global gatsby-cli

      - name: Install  Dependencies
        run: npm install

      - name: Build the Gatsby Project
        run: |
          gatsby --version
          gatsby build
      
      - name: Verify Public folder
        run: ls -la public
     
      - name: Upload public folder as Package
        uses: actions/upload-artifact@v3
        with:
          name: public-package
          path: public
  
  npm-audit:
    name: Npm-audit
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: public-package
          path: public
      
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install  Dependencies
        run: npm install

      - name: Security Component Scanning
        run: npm audit --json > npm-audit-result.json
        continue-on-error: true

      - name: List the FIles available
        run: ls -la

      - name: Archive the npm aduit results output json file
        uses: actions/upload-artifacts@v3
        with:
          name: NPM Audit Output JSON File
          path: npm-audit-result.json
        if: always()

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: npm-audit
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: public-package
          path: public

      - name: copy public to ubuntu
        uses: mdallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: 'public'                                                  # Local file path - REQUIRED false - DEFAULT ./
          remote: '/home/azureuser/'                                                 # Remote file path - REQUIRED false - DEFAULT ~/
          host: ${{secrets.REMOTE_HOST}}                                      # Remote server address - REQUIRED true
          #port: ${{secrets.PORT}}                                      # Remote server port - REQUIRED false - DEFAULT 22
          user: ${{secrets.REMOTE_USER}}                                      # Remote server user - REQUIRED true
          #password: ${{secrets.PASSWORD}}                              # User password - REQUIRED at least one of "password" or "key" 
          key: ${{secrets.SSH_PRIVATEKEY}}                                        # Remote server private key - REQUIRED at least one of "password" or "key" 
          pre_upload: sudo rm -rf /var/www/html/*  # Command to run via ssh before scp upload - REQUIRED false
          post_upload: sudo mv public/* /var/www/html/  # Command to run via ssh after scp upload - REQUIRED false
          ssh_options: -o StrictHostKeyChecking=no                     # A set of ssh_option separated by -o - REQUIRED false - DEFAULT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
          scp_options: -v    