name: Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install  Dependencies
        run: npm install

      - name: Build the Gatsby Project
        run: |
          gatsby --version
          gatsby build
      
      - name: Verify Public folder
        run: ls -la public
     
      - name: Upload public folder as Package
        uses: actions/upload-artifact@v3
        with:
          name: public-package
          path: public