name: Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Install Project Dependencies
        run: npm ci
      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@2.12.34
     
      - name: Build
        run: gatsby build
      
      - name: Verify build
        run: ls -la public
     
      - name: Copy and deploy
        uses: mdallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: 'public'                                                  # Local file path - REQUIRED false - DEFAULT ./
          remote: '/home/azureuser/'                                                 # Remote file path - REQUIRED false - DEFAULT ~/
          host: ${{secrets.REMOTE_HOST}}                                      # Remote server address - REQUIRED true
          port: ${{secrets.PORT}}                                      # Remote server port - REQUIRED false - DEFAULT 22
          user: ${{secrets.REMOTE_USER}}                                      # Remote server user - REQUIRED true
          #password: ${{secrets.PASSWORD}}                              # User password - REQUIRED at least one of "password" or "key" 
          key: ${{secrets.SERVER_SSH_KEY}}                                        # Remote server private key - REQUIRED at least one of "password" or "key" 
          pre_upload: echo "Copy over"  # Command to run via ssh before scp upload - REQUIRED false
          post_upload: sudo mv public/* /var/www/html/  # Command to run via ssh after scp upload - REQUIRED false
          ssh_options: -o StrictHostKeyChecking=no                     # A set of ssh_option separated by -o - REQUIRED false - DEFAULT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
          scp_options: -v